config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'

  get 'login', to: 'users#login'
  get 'logout', to: 'users#logout'
  post 'authenticate', to: 'users#authenticate'

  namespace :api do
    resources :users, only: [:create]
    resources :activities, only: [:index]
    resources :speakers, only: [:index, :show]
    resources :questions, only: [:create, :index] do
      member do
        put :upvote
      end
    end
  end

  namespace :admin do
    root to: 'activities#index'

    resources :activities
    resources :rooms
    resources :speakers
    resources :api_keys
    resources :admins

  end
  
end

app/models/room.rb
class Room < ActiveRecord::Base

  validates :name, presence: true, length: { maximum: 100 }

end

app/controllers/admin/rooms_controller.rb
# encoding: UTF-8
class Admin::RoomsController < Admin::SharedController

  params_for :room, :name

  def index    
    @rooms = Room.page(params[:page])
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)

    if @room.save
      redirect_to admin_rooms_url, notice: 'El salón se ha creado'
    else
      render action: 'new'
    end
  end

  def edit
    @room = Room.find(params[:id])     
  end

  def update
    @room = Room.find(params[:id])

    if @room.update_attributes(room_params)
      redirect_to admin_rooms_url, notice: 'El salón se ha actualizado'
    else
      render action: 'edit'
    end    
  end

  def destroy
    @room = Room.find(params[:id])

    if @room.destroy
      redirect_to admin_rooms_url, notice: 'El salón se ha eliminado'
    else
      redirect_to admin_rooms_url, alert: 'Algo salió mal'
    end
  end
end

app/helpers/admin/rooms_helper.rb
module Admin::RoomsHelper
end

app/views/admin/rooms/_form.html.haml
= render 'admin/shared/form_errors', target: @room

= form_for [:admin, @room], html: {:class => 'form-horizontal', role: 'form'} do |f|
  .form-group
    = f.label :name, 'Nombre', :class => 'control-label col-sm-2'
    .col-sm-10
      = f.text_field :name, :class => 'form-control', placeholder: 'Nombre'

  .form-actions.text-right
    = f.submit 'Continuar', :class => 'btn btn-success'
    = link_to 'Cancelar', admin_rooms_url, :class => 'btn btn-default'
  

app/views/admin/rooms/edit.html.haml
.page-header
    %h1 Editar sal&oacute;n
= render 'form'

app/views/admin/rooms/index.html.haml
.page-header
    %h1 Salones
- if @rooms.any?
    .table-responsive
        %table.table.table-striped
            %thead
                %tr
                    %th Nombre
                    %th Acciones
            %tbody
                - @rooms.each do |room|
                    %tr
                        %td= room.name
                        %td
                            = link_to 'Editar', edit_admin_room_url(room), :class => 'btn btn-default btn-sm'
                            = link_to 'Eliminar', admin_room_url(room), data: {method: :delete, confirm: '¿Estás seguro?'}, :class => 'btn btn-sm btn-danger'
        = pagination(@rooms) 
- else
    %p.well
        No se han encontrado salones                    
%p.text-right
    = link_to 'Agregar', new_admin_room_url, :class => 'btn btn-primary'

app/views/admin/rooms/new.html.haml
.page-header
    %h1 Agregar sal&oacute;n
= render 'form'