config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'

  get 'login', to: 'users#login'
  get 'logout', to: 'users#logout'
  post 'authenticate', to: 'users#authenticate'

  namespace :api do
    resources :users, only: [:create]
    resources :activities, only: [:index]
    resources :speakers, only: [:index, :show]
    resources :questions, only: [:create, :index] do
      member do
        put :upvote
      end
    end
  end

  namespace :admin do
    root to: 'activities#index'

    resources :activities
    resources :rooms
    resources :speakers
    resources :api_keys
    resources :admins

  end
  
end

app/models/speaker.rb
class Speaker < ActiveRecord::Base

  validates :salutation, :company, :name, :bio, presence: true
  validates :salutation, length: { maximum: 10 }
  validates :company, length: { maximum: 100 }
  validates :name, length: { maximum: 100 }

  mount_uploader :photo, PhotoUploader

  has_many :activities  
end

app/controllers/admin/speakers_controller.rb
class Admin::SpeakersController < Admin::SharedController
  params_for :speaker, :salutation, :company, :name, :photo, :bio

  def index    
    @speakers = Speaker.page(params[:page])
  end

  def new
    @speaker = Speaker.new
  end

  def create
    @speaker = Speaker.new(speaker_params)

    if @speaker.save
      redirect_to admin_speakers_url, notice: 'El conferencista se ha creado'
    else
      render action: 'new'
    end
  end

  def edit
    @speaker = Speaker.find(params[:id])     
  end

  def update
    @speaker = Speaker.find(params[:id])

    if @speaker.update_attributes(speaker_params)
      redirect_to admin_speakers_url, notice: 'El conferencista se ha actualizado'
    else
      render action: 'edit'
    end    
  end

  def destroy
    @speaker = Speaker.find(params[:id])

    if @speaker.destroy
      redirect_to admin_speakers_url, notice: 'El conferencista se ha eliminado'
    else
      redirect_to admin_speakers_url, alert: 'Algo salió mal'
    end
  end
end

app/controllers/api/speakers_controller.rb
class Api::SpeakersController < Api::SharedController
  def index
    @speakers = Speaker.includes(:activities).order(:name)
    render json: @speakers.as_json(
      include: {
        activities: { 
          only: [:id, :name, :starts_at, :ends_at ], 
          methods: [:type_name],
          include: { room: { only: [:name] } }
        }
      }
    )
  end

  def show
    @speaker = Speaker.find(params[:id])
    render json: @speaker.as_json(
      include: {
        activities: { 
          only: [:id, :name, :starts_at, :ends_at ], 
          methods: [:type_name],
          include: { room: { only: [:name] } }
        }        
      }
    )
  end
end

app/helpers/admin/speakers_helper.rb
module Admin::SpeakersHelper
end

app/helpers/api/speakers_helper.rb
module Api::SpeakersHelper
end

app/views/admin/speakers/_form.html.haml
= render 'admin/shared/form_errors', target: @speaker

= form_for [:admin, @speaker], multipart: true, html: {:class => 'form-horizontal', role: 'form'} do |f|
    .form-group
        = f.label :salutation, 'Grado', :class => 'control-label col-sm-2'
        .col-sm-10
            = f.text_field :salutation, :class => 'form-control', placeholder: 'Grado'
    .form-group
        = f.label :name, 'Nombre', :class => 'control-label col-sm-2'
        .col-sm-10
            = f.text_field :name, :class => 'form-control', placeholder: 'Nombre'
    .form-group
        = f.label :company, 'Instituci&oacute;n'.html_safe, :class => 'control-label col-sm-2'
        .col-sm-10
            = f.text_field :company, :class => 'form-control', placeholder: 'Instituci&oacute;n'.html_safe
    .form-group
        = f.label :photo, 'Foto', :class => 'control-label col-sm-2'
        .col-sm-10
            = f.file_field :photo, :class => 'form-control'
    .form-group
        = f.label :bio, 'CV', :class => 'control-label col-sm-2'
        .col-sm-10
            = f.text_area :bio, rows: 5, :class => 'form-control', placeholder: 'CV'
    .form-actions.text-right
        = f.submit 'Continuar', :class => 'btn btn-success'
        = link_to 'Cancelar', admin_speakers_url, :class => 'btn btn-default'

app/views/admin/speakers/edit.html.haml
.page-header
    %h1 Editar conferencista
= render 'form'

app/views/admin/speakers/index.html.haml
.page-header
    %h1 Conferencistas
- if @speakers.any?
    .table-responsive
        %table.table.table-striped
            %thead
                %tr
                    %th 
                    %th Nombre
                    %th Instituci&oacute;n
                    %th CV                    
                    %th Acciones
            %tbody
                - @speakers.each do |speaker|
                    %tr
                        %td= image_tag speaker.photo.url, :class => 'img-circle photo-thumb'
                        %td= "#{speaker.salutation} #{speaker.name}"
                        %td= speaker.company
                        %td= truncate speaker.bio, length: 100
                        %td
                            = link_to 'Editar', edit_admin_speaker_url(speaker), :class => 'btn btn-default btn-sm'
                            = link_to 'Eliminar', admin_speaker_url(speaker), data: {method: :delete, confirm: '¿Estás seguro?'}, :class => 'btn btn-sm btn-danger'
        = pagination(@speakers) 
- else
    %p.well
        No se han encontrado conferencistas                    
%p.text-right
    = link_to 'Agregar', new_admin_speaker_url, :class => 'btn btn-primary'

app/views/admin/speakers/new.html.haml
.page-header
    %h1 Agregar conferencista
= render 'form'