config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'

  get 'login', to: 'users#login'
  get 'logout', to: 'users#logout'
  post 'authenticate', to: 'users#authenticate'

  namespace :api do
    resources :users, only: [:create]
    resources :activities, only: [:index]
    resources :speakers, only: [:index, :show]
    resources :questions, only: [:create, :index] do
      member do
        put :upvote
      end
    end
  end

  namespace :admin do
    root to: 'activities#index'

    resources :activities
    resources :rooms
    resources :speakers
    resources :api_keys
    resources :admins

  end
  
end

app/models/activity.rb
class Activity < ActiveRecord::Base

  include Searchable

  TYPES = {
    conference: 0,
    workshop: 1,
    discussion_board: 2,
    paper: 3
  }

  TYPE_NAMES = {
    TYPES[:conference] => 'Conferencia',
    TYPES[:workshop] => 'Taller',
    TYPES[:discussion_board] => 'Panel',
    TYPES[:paper] => 'Ponencia'
  }

  belongs_to :room
  belongs_to :speaker

  validates :name, :activity_type, :description, :starts_at, :ends_at, :room_id, :speaker_id, presence: true
  validates :name, length: { maximum: 100 }
  validate :dates_are_valid

  def type_name
    TYPE_NAMES[self.activity_type]
  end

  def self.search_operators
    {
      name: 'ilike',
      activity_type: '=',
      starts_at: 'between',
      ends_at: 'between',
      room_id: '=',
      speaker_id: '=' 
    }
  end

  def self.time_attributes
    [:starts_at, :ends_at, :created_at, :updated_at]
  end

  protected
    def dates_are_valid
      errors.add(:starts_at, 'La fecha de inicio debe ser menor a la fecha fin') if self.starts_at > self.ends_at
    end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  SALT = 'c0ngr350!'

  validates :name, :email, :encrypted_password, presence: true
  validates :email, uniqueness: true
  validates :password, confirmation: true, if: :needs_password?

  # True if user needs to assign a password
  def needs_password?
    self.new_record? || !self.password.blank?
  end

  # Returns a user with corresponding email and password or nil
  def self.authenticate(email, pwd)
    user = self.find_by(email: email)
    if user
      user = nil unless user.encrypted_password.eql? self.encrypt(pwd, SALT)
    end
    user
  end

  def change_password(current_password, new_password)
    if self.class.encrypt(current_password, SALT).eql? self.encrypted_password
      self.password = new_password
      self.save
    else
      errors.add(:current_password, "no coincide con el password actual")
      false
    end
  end
  
  # Virtual attribute that corresponds to plain-text password
  def password
    @password
  end
  
  # Virtual attribute that corresponds to plain-text password
  def password=(pwd)
    @password = pwd
    self.encrypted_password = self.class.encrypt(pwd,SALT) unless pwd.blank?
  end
  
  
  protected
    
    def self.encrypt(*args)      
      Digest::SHA1.hexdigest(args.join)
    end
end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
  validates :app_name, :key, presence: true
  validates :key, uniqueness: true

  before_validation(on: :create) do
    generate_key
  end

  def generate_key
    begin
      self.key = SecureRandom.hex
    end while self.class.exists?(key: self.key)
  end
end

app/models/concerns/searchable.rb
module Searchable

  extend ActiveSupport::Concern

  module ClassMethods
    def search(data)
      query = all
      self.search_operators.each_pair do |attribute, operator|
        if operator.is_a? Hash
          query = self.search_with_scope(data, attribute, query)
        else
          query = self.search_attribute(self.table_name, attribute, operator, data[attribute], query)
        end
      end 
      query   
    end
    
    protected

    def search_with_scope(data, scope, query)
      self.search_operators[scope].each_pair do |attribute, operator|
        attribute_name = self.get_scoped_attribute(scope, attribute)
        query = self.search_attribute(scope, attribute, operator, data[attribute_name], query)
      end
      query
    end

    def get_scoped_attribute(scope, attribute)
      "#{scope.to_s.singularize}_#{attribute}"
    end

    def search_attribute(scope,attribute,operator,value,query)
      unless value.blank?
        if operator.eql? 'between'
          query = self.search_between(scope,attribute,operator,value,query) 
        else
          value = "%#{value}%" if operator.eql? 'ilike'      
          query = query.where("#{scope}.#{attribute} #{operator} ?", value_for_attribute(value, attribute))
        end     
      end
      query
    end

    def search_between(scope,attribute,operator,value,query)
      unless value[:start].blank? or value[:end].blank?
        query = query.where("#{scope}.#{attribute} #{operator} ? AND ?", self.value_for_attribute(value[:start], attribute), self.value_for_attribute(value[:end], attribute))  
      end
      query
    end

    def value_for_attribute(value, attribute)
      if(self.time_attributes.include? attribute)
        value = Time.parse(value)
      end
      value
    end
    
  end
end

app/models/question.rb
class Question < ActiveRecord::Base

  belongs_to :user
  belongs_to :activity

  validates :text, :votes, :activity_id, :user_id, presence: true
  validates :votes, numericality: { only_integer: true }
  validates :text, length: { maximum: 150 }

  after_create :publish_question

  include Searchable

  def self.search_operators
    {
      user_id: '=',
      activity_id: '='
    }
  end

  def self.time_attributes
    [:created_at, :updated_at]
  end

  protected
    def publish_question
      PrivatePub.publish_to "/questions", question: self.as_json(
        include: {
          user: { only: [:full_name] }, 
          activity: { only: [:name] }
        }
      )
    end
end

app/models/room.rb
class Room < ActiveRecord::Base

  validates :name, presence: true, length: { maximum: 100 }

end

app/models/speaker.rb
class Speaker < ActiveRecord::Base

  validates :salutation, :company, :name, :bio, presence: true
  validates :salutation, length: { maximum: 10 }
  validates :company, length: { maximum: 100 }
  validates :name, length: { maximum: 100 }

  mount_uploader :photo, PhotoUploader

  has_many :activities  
end

app/models/user.rb
class User < ActiveRecord::Base

  validates :email, :full_name, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  extend ParamsFor
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @activities = Activity.order(:name)    
  end
end

app/controllers/users_controller.rb
# encoding UTF-8
class UsersController < ApplicationController
  def login
    if session[:admin_id]
      redirect_to admin_root_url
    end
  end

  def logout
    reset_session
    redirect_to root_url
  end

  def authenticate
    @admin = Admin.authenticate(params[:email], params[:password])
    if @admin
      session[:admin_id] = @admin.id
      redirect_to admin_root_url
    else
      flash[:alert] = 'Usuario / Contraseña incorrectos'
      redirect_to login_url
    end
  end
end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/rooms_helper.rb
module Admin::RoomsHelper
end

app/helpers/admin/shared_helper.rb
module Admin::SharedHelper
end

app/helpers/api/shared_helper.rb
module Api::SharedHelper
end

app/helpers/api/speakers_helper.rb
module Api::SpeakersHelper
end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  ALERT_TYPES = [:danger, :info, :success, :warning]

  def pagination(collection, options={})
    will_paginate collection, options.merge(renderer: BootstrapPagination::Rails)
  end

  def bootstrap_flash
    output = ''
    
    flash.each do |type, message|
      Rails.logger.info "[INFO] #{type} => #{message}"
      next if message.blank?
      type = :success if type == :notice
      type = :danger   if type == :alert
      next unless ALERT_TYPES.include?(type)
      output += flash_container(type, message)
    end
    Rails.logger.info "[INFO] #{output}"
    raw(output)
  end

  def flash_container(type, message)
    raw(content_tag(:div, :class => "bootstrap-flash alert alert-#{type}") do
      content_tag(:a, raw("&times;"),:class => 'close', :data => {:dismiss => 'alert'}) +
      message.html_safe
    end)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/admins/_form.html.haml
= render 'admin/shared/form_errors', target: @admin

= form_for [:admin, @admin], html: {:class => 'form-horizontal', role: 'form'} do |f|
    .form-group
        = f.label :name, 'Nombre', :class => 'control-label col-sm-2'
        .col-sm-10
            = f.text_field :name, :class => 'form-control', placeholder: 'Nombre'
    .form-group   
        = f.label :email, 'Email', :class => 'control-label col-sm-2'
        .col-sm-10
            = f.email_field :email, :class => 'form-control', placeholder: 'Email'
    .form-group   
        = f.label :password, 'Password', :class => 'control-label col-sm-2'
        .col-sm-10
            = f.password_field :password, :class => 'form-control', placeholder: 'Password'
    .form-group   
        = f.label :password_confirmation, 'Confirma Password', :class => 'control-label col-sm-2'
        .col-sm-10
            = f.password_field :password_confirmation, :class => 'form-control', placeholder: 'Password'

    .form-actions.text-right
        = f.submit 'Continuar', :class => 'btn btn-success'
        = link_to 'Cancelar', admin_admins_url, :class => 'btn btn-default'
  

app/views/admin/admins/edit.html.haml
.page-header
    %h1 Editar Administrador
= render 'form'

app/views/admin/admins/index.html.haml
.page-header
    %h1 Administradores
- if @admins.any?
    .table-responsive
        %table.table.table-striped
            %thead
                %tr
                    %th Nombre
                    %th Email
                    %th Acciones
            %tbody
                - @admins.each do |admin|
                    %tr
                        %td= admin.name
                        %td= admin.email
                        %td
                            = link_to 'Editar', edit_admin_admin_url(admin), :class => 'btn btn-default btn-sm'
                            = link_to 'Eliminar', admin_admin_url(admin), data: {method: :delete, confirm: '¿Estás seguro?'}, :class => 'btn btn-sm btn-danger'
        = pagination(@admins) 
- else
    %p.well
        No se han encontrado administradores                    
%p.text-right
    = link_to 'Agregar', new_admin_admin_url, :class => 'btn btn-primary'

app/views/admin/admins/new.html.haml
.page-header
    %h1 Agregar Administrador
= render 'form'

app/views/layouts/application.html.haml
!!! 5
%html
    %head
        %title II Congreso Internacional de Tecnologías Emergentes en Educación e Informática
        = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
        = yield :stylesheets
        
        = javascript_include_tag 'application', 'data-turbolinks-track' => true
        = yield :javascripts
        = csrf_meta_tags
    %body(ng-app="congreso")
        = yield

app/views/layouts/backend.html.haml
!!! 5
%html
    %head
        %title Congreso
        = stylesheet_link_tag 'backend', media: 'all', 'data-turbolinks-track' => true
        = yield :stylesheets
        
        = javascript_include_tag 'application', 'data-turbolinks-track' => true
        = yield :javascripts
        = csrf_meta_tags
    %body
        .navbar.navbar-inverse.navbar-static-top(role="navigation")
            .container
                .navbar-header
                    %button.navbar-toggle{data: {toggle: 'collapse', target: '#navbar-collapse'}}
                        %i.icon-reorder
                    = link_to 'Congreso', '#', :class => 'navbar-brand'
                .collapse.navbar-collapse#navbar-collapse
                    %ul.nav.navbar-nav.navbar-right
                        %li= link_to 'Actividades', admin_activities_url
                        %li= link_to 'Conferencistas', admin_speakers_url
                        %li= link_to 'Salones', admin_rooms_url
                        %li= link_to 'API Keys', admin_api_keys_url
                        %li= link_to 'Administradores', admin_admins_url
                        %li= link_to 'Logout', logout_url
        .container    
            = yield