config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'

  get 'login', to: 'users#login'
  get 'logout', to: 'users#logout'
  post 'authenticate', to: 'users#authenticate'

  namespace :api do
    resources :users, only: [:create]
    resources :activities, only: [:index]
    resources :speakers, only: [:index, :show]
    resources :questions, only: [:create, :index] do
      member do
        put :upvote
      end
    end
  end

  namespace :admin do
    root to: 'activities#index'

    resources :activities
    resources :rooms
    resources :speakers
    resources :api_keys
    resources :admins

  end
  
end

app/models/activity.rb
class Activity < ActiveRecord::Base

  include Searchable

  TYPES = {
    conference: 0,
    workshop: 1,
    discussion_board: 2,
    paper: 3
  }

  TYPE_NAMES = {
    TYPES[:conference] => 'Conferencia',
    TYPES[:workshop] => 'Taller',
    TYPES[:discussion_board] => 'Panel',
    TYPES[:paper] => 'Ponencia'
  }

  belongs_to :room
  belongs_to :speaker

  validates :name, :activity_type, :description, :starts_at, :ends_at, :room_id, :speaker_id, presence: true
  validates :name, length: { maximum: 100 }
  validate :dates_are_valid

  def type_name
    TYPE_NAMES[self.activity_type]
  end

  def self.search_operators
    {
      name: 'ilike',
      activity_type: '=',
      starts_at: 'between',
      ends_at: 'between',
      room_id: '=',
      speaker_id: '=' 
    }
  end

  def self.time_attributes
    [:starts_at, :ends_at, :created_at, :updated_at]
  end

  protected
    def dates_are_valid
      errors.add(:starts_at, 'La fecha de inicio debe ser menor a la fecha fin') if self.starts_at > self.ends_at
    end

end

app/controllers/admin/activities_controller.rb
class Admin::ActivitiesController < Admin::SharedController

  before_filter :get_select_collections, only: [:edit, :new]
  params_for :activity, :name, :activity_type, :description, :starts_at, :ends_at, :room_id, :speaker_id

  def index    
    @activities = Activity.includes(:speaker, :room).page(params[:page])
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)

    if @activity.save
      redirect_to admin_activities_url, notice: 'La actividad se ha creado'
    else
      get_select_collections
      render action: 'new'
    end
  end

  def edit
    @activity = Activity.find(params[:id])     
  end

  def update
    @activity = Activity.find(params[:id])

    if @activity.update_attributes(activity_params)
      redirect_to admin_activities_url, notice: 'La actividad se ha actualizado'
    else
      get_select_collections
      render action: 'edit'
    end    
  end

  def destroy
    @activity = Activity.find(params[:id])

    if @activity.destroy
      redirect_to admin_activities_url, notice: 'La actividad se ha eliminado'
    else
      redirect_to admin_activities_url, alert: 'Algo salió mal'
    end
  end

  protected
    def get_select_collections
      @speakers = Speaker.order(:name)
      @rooms = Room.order(:name)
    end
end

app/controllers/api/activities_controller.rb
class Api::ActivitiesController < Api::SharedController
  def index
    @activities = Activity.search(params).includes(:speaker, :room).order(:starts_at)
    render json: @activities.as_json(
      methods: [ :type_name ],
      include: {
        speaker: { only: [:id, :salutation, :name, :photo] },
        room: { only: [:id, :name] }
      }
    )
  end
end

app/helpers/admin/activities_helper.rb
module Admin::ActivitiesHelper

  def activity_type_options
    Activity::TYPE_NAMES.map do |key, value|
      [value, key]
    end
  end
end

app/helpers/api/activities_helper.rb
module Api::ActivitiesHelper
end

app/views/admin/activities/_form.html.haml
= render 'admin/shared/form_errors', target: @activity

= form_for [:admin, @activity], html: {:class => 'form-horizontal', role: 'form'} do |f|
  .form-group
    = f.label :name, 'Nombre', :class => 'control-label col-sm-2'
    .col-sm-10
      = f.text_field :name, :class => 'form-control', placeholder: 'Nombre'
  .form-group
    = f.label :activity_type, 'Tipo de Actividad', :class => 'control-label col-sm-2'
    .col-sm-10
      = f.select :activity_type, activity_type_options, {}, :class => 'form-control'
  .form-group
    = f.label :description, 'Descripci&oacute;n'.html_safe, :class => 'control-label col-sm-2'
    .col-sm-10
      = f.text_area :description, rows: 5, :class => 'form-control'
  .form-group
    = f.label :starts_at, 'Fecha Inicio', :class => 'control-label col-sm-2'
    .col-sm-10
      = f.datetime_select :starts_at, {}, :class => 'form-control'
  .form-group
    = f.label :ends_at, 'Fecha Fin', :class => 'control-label col-sm-2'
    .col-sm-10
      = f.datetime_select :ends_at, {}, :class => 'form-control'
  .form-group
    = f.label :room_id, 'Sal&oacute;n'.html_safe, :class => 'control-label col-sm-2'
    .col-sm-10
      = f.select :room_id, options_from_collection_for_select(@rooms, :id, :name, @activity.room_id), {prompt: 'Seleccione'}, :class => 'form-control'
  .form-group
    = f.label :speaker_id, 'Conferencista'.html_safe, :class => 'control-label col-sm-2'
    .col-sm-10
      = f.select :speaker_id, options_from_collection_for_select(@speakers, :id, :name, @activity.speaker_id), {prompt: 'Seleccione'}, :class => 'form-control'

  .form-actions.text-right
    = f.submit 'Continuar', :class => 'btn btn-success'
    = link_to 'Cancelar', admin_activities_url, :class => 'btn btn-default'
  

app/views/admin/activities/edit.html.haml
.page-header
    %h1 Editar actividad
= render 'form'

app/views/admin/activities/index.html.haml
.page-header
    %h1 Actividades
- if @activities.any?
    .table-responsive
        %table.table.table-striped
            %thead
                %tr
                    %th Nombre
                    %th Tipo de Actividad
                    %th Conferencista
                    %th Sal&oacute;n
                    %th Fecha Inicio
                    %th Fecha Fin
                    %th Acciones
            %tbody
                - @activities.each do |activity|
                    %tr
                        %td= activity.name
                        %td= activity.type_name
                        %td= activity.speaker.name
                        %td= activity.room.name
                        %td= activity.starts_at
                        %td= activity.ends_at
                        %td
                            = link_to 'Editar', edit_admin_activity_url(activity), :class => 'btn btn-default btn-sm'
                            = link_to 'Eliminar', admin_activity_url(activity), data: {method: :delete, confirm: '¿Estás seguro?'}, :class => 'btn btn-sm btn-danger'
        = pagination(@activities) 
- else
    %p.well
        No se han encontrado actividades                    
%p.text-right
    = link_to 'Agregar', new_admin_activity_url, :class => 'btn btn-primary'

app/views/admin/activities/new.html.haml
.page-header
    %h1 Agregar actividad
= render 'form'